const userConstants = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  REFRESH: "REFRESH",
  LOGOUT: "LOGOUT",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_ALL: "GET_ALL",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  UPDATE_USER: "UPDATE_USER",
  FILTER: "FILTER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  CREATE_CONTRACT:"CREATE_CONTRACT",
};

export default userConstants;
